// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  actorId: __t.u64().primaryKey().name("actor_id"),
  status: __t.string(),
  markedEquityCents: __t.u64().name("marked_equity_cents"),
  lifetimePnlCents: __t.i64().name("lifetime_pnl_cents"),
  wipeoutCount: __t.u64().name("wipeout_count"),
  lastStepTick: __t.option(__t.u64()).name("last_step_tick"),
});
