// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  tick: __t.u64(),
  price: __t.u64(),
  logicalTick: __t.u64().name("logical_tick"),
  epoch: __t.u64(),
  priceCents: __t.u64().name("price_cents"),
  previousTradedPriceCents: __t.u64().name("previous_traded_price_cents"),
  matchedShareVolume: __t.u64().name("matched_share_volume"),
  volatilityBps: __t.u64().name("volatility_bps"),
  actorCount: __t.u64().name("actor_count"),
  activeActorCount: __t.u64().name("active_actor_count"),
  registeredHumanTraderCount: __t.u64().name("registered_human_trader_count"),
  connectedIdentityCount: __t.u64().name("connected_identity_count"),
  cumulativeActorSteps: __t.u64().name("cumulative_actor_steps"),
  cumulativePolicyEvaluations: __t.u64().name("cumulative_policy_evaluations"),
  cumulativeActorRowsUpdated: __t.u64().name("cumulative_actor_rows_updated"),
  cumulativeOrdersSubmitted: __t.u64().name("cumulative_orders_submitted"),
  cumulativeOrdersFilled: __t.u64().name("cumulative_orders_filled"),
  cumulativeMatchedShareVolume: __t.u64().name("cumulative_matched_share_volume"),
  rateWindowUs: __t.u64().name("rate_window_us"),
  rateWindowStartedAt: __t.timestamp().name("rate_window_started_at"),
  rateWindowEndedAt: __t.timestamp().name("rate_window_ended_at"),
  chaosActive: __t.bool().name("chaos_active"),
  phase: __t.string(),
  configurationHash: __t.string().name("configuration_hash"),
});
