// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  referencePriceCents: __t.u64().name("reference_price_cents"),
  sentimentBps: __t.i64().name("sentiment_bps"),
  mode: __t.string(),
  floorStreak: __t.u64().name("floor_streak"),
  illiquidStreak: __t.u64().name("illiquid_streak"),
  healthyStreak: __t.u64().name("healthy_streak"),
  distressedBuckets: __t.u64().name("distressed_buckets"),
  episode: __t.u64(),
  episodeStartedTick: __t.u64().name("episode_started_tick"),
  nextRecoveryTick: __t.u64().name("next_recovery_tick"),
  revivedActors: __t.u64().name("revived_actors"),
  episodeGrantsCents: __t.u128().name("episode_grants_cents"),
  totalGrantsCents: __t.u128().name("total_grants_cents"),
  constrainedGrants: __t.u64().name("constrained_grants"),
});
