// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity(),
  orderKey: __t.u64().name("order_key"),
  clientOrderId: __t.u64().name("client_order_id"),
  buy: __t.bool(),
  quantity: __t.u64(),
  limitPriceCents: __t.u64().name("limit_price_cents"),
  acceptedAt: __t.timestamp().name("accepted_at"),
});
