// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  identity: __t.identity(),
  clientOrderId: __t.u64().name("client_order_id"),
  sequence: __t.u64(),
  logicalTick: __t.u64().name("logical_tick"),
  buy: __t.bool(),
  requestedQuantity: __t.u64().name("requested_quantity"),
  filledQuantity: __t.u64().name("filled_quantity"),
  priceCents: __t.u64().name("price_cents"),
  status: __t.string(),
  recordedAt: __t.timestamp().name("recorded_at"),
});
