// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity(),
  cashCents: __t.u64().name("cash_cents"),
  shares: __t.u64(),
  reservedCashCents: __t.u64().name("reserved_cash_cents"),
  reservedShares: __t.u64().name("reserved_shares"),
  pnlCents: __t.i64().name("pnl_cents"),
  createdAt: __t.timestamp().name("created_at"),
  lastOrderAt: __t.option(__t.timestamp()).name("last_order_at"),
  completedOrders: __t.u64().name("completed_orders"),
});
