// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  headline: __t.string(),
  direction: __t.i8(),
  severityBps: __t.u64().name("severity_bps"),
  confidenceBps: __t.u64().name("confidence_bps"),
  startTick: __t.u64().name("start_tick"),
  endTick: __t.u64().name("end_tick"),
});
