// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  logicalTick: __t.u64().primaryKey().name("logical_tick"),
  recordedAt: __t.timestamp().name("recorded_at"),
  priceCents: __t.u64().name("price_cents"),
  matchedShareVolume: __t.u64().name("matched_share_volume"),
});
