// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  logicalTick: __t.u64().name("logical_tick"),
  recordedAt: __t.timestamp().name("recorded_at"),
  participantType: __t.string().name("participant_type"),
  participantId: __t.string().name("participant_id"),
  eventKind: __t.string().name("event_kind"),
  side: __t.string(),
  quantity: __t.u64(),
  priceCents: __t.u64().name("price_cents"),
  lifetimePnlCents: __t.i64().name("lifetime_pnl_cents"),
  wipeoutCount: __t.u64().name("wipeout_count"),
});
