#!/usr/bin/env bash
source "$(dirname "$0")/common.sh"

compose run --rm --no-deps tools spacetime --root-dir /state generate \
  --module-path crates/spacetime --lang typescript \
  --out-dir packages/bindings/src --no-config --yes
compose run --rm --no-deps tools spacetime --root-dir /state generate \
  --bin-path target/wasm32-unknown-unknown/release/one_market_spacetime.wasm \
  --lang rust --include-private --out-dir crates/benchmark/src/bindings --no-config --yes
